"""add company currency_code

Revision ID: 0f1f2d646f73
Revises: 7319575dbfe9
Create Date: 2026-08-12 19:54:27.752356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1f2d646f73'
down_revision: Union[str, Sequence[str], None] = '7319575dbfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default required: `company` already has production rows; MXN preserves the
    # existing implicit currency for them.
    op.add_column('company', sa.Column('currency_code', sa.String(), nullable=False, server_default='MXN'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'currency_code')
    # ### end Alembic commands ###
