"""add media transform (adstock + hill)

Revision ID: 6b0ac33ad4d4
Revises: fffc97010661
Create Date: 2026-08-03 18:35:52.084581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b0ac33ad4d4'
down_revision: Union[str, Sequence[str], None] = 'fffc97010661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modeltransform',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variable_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decay', sa.Float(), nullable=False),
    sa.Column('hill_k', sa.Float(), nullable=False),
    sa.Column('hill_s', sa.Float(), nullable=False),
    sa.Column('lag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'variable_name', name='uq_model_transform_model_var')
    )
    op.create_index(op.f('ix_modeltransform_company_id'), 'modeltransform', ['company_id'], unique=False)
    op.create_index(op.f('ix_modeltransform_model_id'), 'modeltransform', ['model_id'], unique=False)
    # server_default is required here (not just the SQLModel-level default) because these
    # tables already have production rows (existing Group/Subgroup catalog entries) — a
    # NOT NULL column added without one would fail against them.
    op.add_column('group', sa.Column('apply_media_transform', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('subgroup', sa.Column('apply_media_transform', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subgroup', 'apply_media_transform')
    op.drop_column('group', 'apply_media_transform')
    op.drop_index(op.f('ix_modeltransform_model_id'), table_name='modeltransform')
    op.drop_index(op.f('ix_modeltransform_company_id'), table_name='modeltransform')
    op.drop_table('modeltransform')
    # ### end Alembic commands ###
