"""add per-model apply_media_transforms toggle

Revision ID: 7f4d461579cd
Revises: 6b0ac33ad4d4
Create Date: 2026-08-03 19:11:59.115463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4d461579cd'
down_revision: Union[str, Sequence[str], None] = '6b0ac33ad4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: `model` already has production rows, and the default (True)
    # preserves the existing automatic behavior for them if they're ever re-fit.
    op.add_column('model', sa.Column('apply_media_transforms', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'apply_media_transforms')
    # ### end Alembic commands ###
