"""add investment channel catalog and model economics fields

Revision ID: 9373a11759cc
Revises: a1b2c3d4e5f6
Create Date: 2026-08-04 18:54:34.294301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9373a11759cc'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investmentchannel',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proxy_variable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dataset_id', 'name', name='uq_invchannel_company_dataset_name')
    )
    op.create_index(op.f('ix_investmentchannel_company_id'), 'investmentchannel', ['company_id'], unique=False)
    op.create_index(op.f('ix_investmentchannel_dataset_id'), 'investmentchannel', ['dataset_id'], unique=False)
    op.add_column('model', sa.Column('conversion_rate', sa.Float(), nullable=True))
    op.add_column('model', sa.Column('avg_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # New tables need RLS enabled in the same migration that creates them (see
    # a1b2c3d4e5f6) — no policies defined on purpose (deny-by-default; the app connects as
    # the table owner, which always bypasses RLS, per tenancy.py). Postgres-only syntax,
    # skipped on the local SQLite dev fallback.
    if op.get_bind().dialect.name == "postgresql":
        op.execute('ALTER TABLE "investmentchannel" ENABLE ROW LEVEL SECURITY')


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute('ALTER TABLE "investmentchannel" DISABLE ROW LEVEL SECURITY')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'avg_value')
    op.drop_column('model', 'conversion_rate')
    op.drop_index(op.f('ix_investmentchannel_dataset_id'), table_name='investmentchannel')
    op.drop_index(op.f('ix_investmentchannel_company_id'), table_name='investmentchannel')
    op.drop_table('investmentchannel')
    # ### end Alembic commands ###
