"""initial schema

Revision ID: fffc97010661
Revises: 
Create Date: 2026-07-30 18:49:05.331070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fffc97010661'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('columns_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('time_variable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('previous_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'file_name', 'checksum', name='uq_dataset_company_file_checksum')
    )
    op.create_index(op.f('ix_dataset_company_id'), 'dataset', ['company_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_company_id'), 'group', ['company_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_membership_user_company')
    )
    op.create_index(op.f('ix_membership_company_id'), 'membership', ['company_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('model',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('y_var', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x_vars_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_hero', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_company_id'), 'model', ['company_id'], unique=False)
    op.create_index(op.f('ix_model_dataset_id'), 'model', ['dataset_id'], unique=False)
    op.create_table('modelmetrics',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('r2', sa.Float(), nullable=False),
    sa.Column('adj_r2', sa.Float(), nullable=False),
    sa.Column('durbin_watson', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('vif_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_modelmetrics_company_id'), 'modelmetrics', ['company_id'], unique=False)
    op.create_table('scenario',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adjustments_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_company_id'), 'scenario', ['company_id'], unique=False)
    op.create_index(op.f('ix_scenario_model_id'), 'scenario', ['model_id'], unique=False)
    op.create_table('subgroup',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgroup_company_id'), 'subgroup', ['company_id'], unique=False)
    op.create_index(op.f('ix_subgroup_group_id'), 'subgroup', ['group_id'], unique=False)
    op.create_table('variable',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dtype', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('source_spec_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subgroup_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variable_company_id'), 'variable', ['company_id'], unique=False)
    op.create_index(op.f('ix_variable_dataset_id'), 'variable', ['dataset_id'], unique=False)
    op.create_table('variablehistory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variable_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variablehistory_company_id'), 'variablehistory', ['company_id'], unique=False)
    op.create_index(op.f('ix_variablehistory_dataset_id'), 'variablehistory', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_variablehistory_variable_id'), 'variablehistory', ['variable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variablehistory_variable_id'), table_name='variablehistory')
    op.drop_index(op.f('ix_variablehistory_dataset_id'), table_name='variablehistory')
    op.drop_index(op.f('ix_variablehistory_company_id'), table_name='variablehistory')
    op.drop_table('variablehistory')
    op.drop_index(op.f('ix_variable_dataset_id'), table_name='variable')
    op.drop_index(op.f('ix_variable_company_id'), table_name='variable')
    op.drop_table('variable')
    op.drop_index(op.f('ix_subgroup_group_id'), table_name='subgroup')
    op.drop_index(op.f('ix_subgroup_company_id'), table_name='subgroup')
    op.drop_table('subgroup')
    op.drop_index(op.f('ix_scenario_model_id'), table_name='scenario')
    op.drop_index(op.f('ix_scenario_company_id'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_modelmetrics_company_id'), table_name='modelmetrics')
    op.drop_table('modelmetrics')
    op.drop_index(op.f('ix_model_dataset_id'), table_name='model')
    op.drop_index(op.f('ix_model_company_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_company_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_group_company_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_dataset_company_id'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_table('company')
    # ### end Alembic commands ###
